apiVersion: v1
kind: Service
metadata:
  name: ceph-mon-nodeport
  namespace: rook-ceph
spec:
  type: NodePort
  selector:
    app: rook-ceph-mon
  ports:
    - port: 6789
      protocol: TCP
      nodePort: 30000
---
apiVersion: v1
kind: Namespace
metadata:
  name: ceph-test
---
apiVersion: v1
kind: Secret
metadata:
  name: ceph-admin
  namespace: ceph-test
data:
  # ceph auth get-key client.admin | base64
  key: QVFCbll3QmVWR2UxQ3hBQVVGV0lHK1lDSmY4UEpDbzJWNEVWVGc9PQ==
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ceph
  namespace: ceph-test
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  rbd:
    monitors:
      - 127.0.0.1:30000
    pool: kubernetes
    image: pv-vol
    user: admin
    secretRef:
      name: ceph-admin
    fsType: ext4
    readOnly: false
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: ceph
  namespace: ceph-test
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: ceph
---
apiVersion: v1
kind: Pod
metadata:
  name: ceph-test
  namespace: ceph-test
spec:
  containers:
    - name: ceph-test
      image: busybox
      args:
        - tail
        - -f
        - /dev/null
      volumeMounts:
        - name: ceph
          mountPath: /var/lib/ceph
  volumes:
    - name: ceph
      persistentVolumeClaim:
        claimName: ceph