# ref: https://kind.sigs.k8s.io/docs/user/configuration/
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
#  - |
#    kind: ClusterConfiguration
#    metadata:
#      name: config
#    apiServer:
#      extraArgs:
#        "feature-gates": "FeatureGateName=true"
#    scheduler:
#      extraArgs:
#        "feature-gates": "FeatureGateName=true"
#    controllerManager:
#      extraArgs:
#        "feature-gates": "FeatureGateName=true"
#  - |
#    kind: InitConfiguration
#    metadata:
#      name: config
#    nodeRegistration:
#      kubeletExtraArgs:
#        "feature-gates": "FeatureGateName=true"
#  - |
#    kind: KubeletConfiguration
#    featureGates:
#      FeatureGateName: true
#  - |
#    kind: KubeProxyConfiguration
#    featureGates:
#      FeatureGateName: true
nodes:
  - role: control-plane
  - role: worker
  - role: worker
